gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000
    firewall: api
    return_expiration: true
    single_use: true
#    user_checker: user_checker_service_id
